name: vocab_trainer_app
description: Long-term vocabulary trainer that works on your own schedule.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  logger: ^1.3.0
  sqflite: ^2.2.8+2
  path: ^1.8.2
  flutter_svg: ^2.0.5
  shared_preferences: ^2.1.1
  cherry_toast: ^1.2.1
  retry: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loads/
    - assets/icons/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Jost
      fonts:
        - asset: fonts/Jost/static/Jost-Thin.ttf
          weight: 100
        - asset: fonts/Jost/static/Jost-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: fonts/Jost/static/Jost-ExtraLight.ttf
          weight: 200
        - asset: fonts/Jost/static/Jost-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Jost/static/Jost-Light.ttf
          weight: 300
        - asset: fonts/Jost/static/Jost-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Jost/static/Jost-Regular.ttf
          weight: 400
        - asset: fonts/Jost/static/Jost-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Jost/static/Jost-Medium.ttf
          weight: 500
        - asset: fonts/Jost/static/Jost-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Jost/static/Jost-SemiBold.ttf
          weight: 600
        - asset: fonts/Jost/static/Jost-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Jost/static/Jost-Bold.ttf
          weight: 700
        - asset: fonts/Jost/static/Jost-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Jost/static/Jost-ExtraBold.ttf
          weight: 800
        - asset: fonts/Jost/static/Jost-ExtraBoldItalic.ttf
          weight: 800
          style: italic
