const allLanguages = [
  "Afrikaans",
  "Cantonese",
  "English",
  "Esperanto",
  "French",
  "German",
  "Hebrew",
  "Hindu",
  "Italian",
  "Japanese",
  "Korean",
  "Mandarin (Simplified)",
  "Mandarin (Traditional)",
  "Moldovan",
  "Mongolian",
  "Portuguese",
  "Portuguese (Brazilian)",
  "Russian",
  "Spanish",
  "Spanish (Spain)",
  "Spanish (Mexico)",
  "Spanish (Castilian)",
  "Ukrainian",
];
